### ISSUE TITLE
Add following link

### ISSUE THREAD

**Issue by AzureEzy** [ashishrajsrivastava/learningresources#2]
🎁Free Real Python Course Bundle  

Link : https://bit.ly/2WKvj74

code: https://bit.ly/39mmToT

Clicking the link above gives you lifetime access to the following video courses on Real Python.

-How to Publish Your Own Python Package to PyPI
-Traditional Face Detection With Python
-Functional Programming in Python
-Cool New Features in Python 3.8

**Comment by ashishrajsrivastava** [comment]
Already added
